name: docs

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: start build notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: html
          message: |
            ‚è≥ <a href="${{ github.server_url }}/${{ github.repository }}"><b>${{ github.repository }}</b></a>

            ${{ github.workflow }}

            by: ${{ github.actor }}
            branch: ${{ github.ref }}
            commit: ${{ github.event.head_commit.message }}
            sha: ${{ steps.vars.outputs.sha_short }}

            <a href="${{ github.event.head_commit.url }}">link</a>

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: build
        run: pnpm run docs:build

      - name: deploy to netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './docs/.vitepress/dist'
          production-branch: main
          deploy-message: 'deploy from github actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

      - name: finish build notification
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: html
          message: |
            ${{ job.status == 'success' && '‚úÖ' || 'üÜò' }} <a href="${{ github.server_url }}/${{ github.repository }}"><b>${{ github.repository }}</b></a>

            ${{ github.workflow }}

            by: ${{ github.actor }}
            branch: ${{ github.ref }}
            commit: ${{ github.event.head_commit.message }}
            sha: ${{ steps.vars.outputs.sha_short }}

            <a href="${{ github.event.head_commit.url }}">link</a>
